### ISSUE TITLE
Detect finished races

### ISSUE THREAD

**Issue by stuff1993** [stuff1993/ArbBetSystem#5]
Need to detect races that have run and exclude them from future checks.
Potentially disable them in UI

**Comment by jordansidhom** [comment]
Maybe 1 min after it has closed, as you can still bet right up to the last second, and some bookmakers dont close until literally jump time. Some races get delayed so it may appear to have started but it hasnt actually.

**Comment by stuff1993** [comment]
Events are still able to be checked in UI but threads are not spawned if the Event has already run.
Threads die once event has run and past the configured grace period.
