### ISSUE TITLE
Logging in after midnight wont show UK races

### ISSUE THREAD

**Issue by jordansidhom** [stuff1993/ArbBetSystem#6]
Logging in after midnight won't show the UK races from (technically) previous day (UK time). 
If logged in at 11pm AEST it will show all the UK races (even ones that start at 3am AEST the next day).  Must be because UK time is still previous day. 
If logged in at 12am AEST (following day) it won't show the UK races.

If show Todays races + yesterdays races i'm worried it will cause issues is same meeting is on 2 days in a row. Maybe suggested show todays races + races 12 hours previous?

**Comment by stuff1993** [comment]
See #4
